import re


class TechCounter:
	def __init__(self, name, regex, category, count=0):
		self.name = name
		self.regex = re.compile(regex, re.IGNORECASE|re.MULTILINE)
		self.category = category
		self.count = count
		self.graph_percentage = None

	def __repr__(self):
		return self.name

	def match(self, string):
		if self.regex.search(string):
			return True


def new_tech_list():
	return [
		TechCounter('Assembly', r'^(.+?[ <>\n])?assembly([ <>\n].+?)?$', 'Languages'),
		TechCounter('Bash', r'^(.+?[ <>\n])?bash([ <>\n].+?)?$', 'Languages'),
		TechCounter('C', r'^(.+?[ <>\n])?c([ <>\n].+?)?$', 'Languages'),
		TechCounter('C++', r'^(.+?[ <>\n])?c\+\+([- ]?\d+)?([ <>\n].+?)?$', 'Languages'),
		TechCounter('C#', r'^(.+?[ <>\n])?c#([ <>\n].+?)?$', 'Languages'),
		TechCounter('Clojure', r'^(.+?[ <>\n])?clojure([ <>\n].+?)?$', 'Languages'),
		TechCounter('Java', r'^(.+?[ <>\n])?java([- ]([ <>\n]+|\d))?([ <>\n].+?)?$', 'Languages'),
		TechCounter('Python', r'^(.+?[ <>\n])?python([ <>\n].+?)?$', 'Languages'),
		TechCounter(
			'JavaScript',
			r'^(.+?[ <>\n])?javascript([ <>\n].+?)?$|^(.+?[ <>\n])?es([- ]?\d)?([ <>\n].+?)?$|^(.+?[ <>\n])?ecmascript([- ]?\d)?([ <>\n].+?)?$|^(.+?[ <>\n])?js([ <>\n].+?)?$',
			'Languages'
		),
		TechCounter('SQL', r'^(.+?[ <>\n])?sql([ <>\n].+?)?$', 'Languages'),
		TechCounter('HTML', r'^(.+?[ <>\n])?html(\d)?([ <>\n].+?)?', 'Languages'),
		TechCounter('CSS', r'^(.+?[ <>\n])?css(\d)?([ <>\n].+?)?', 'Languages'),
		TechCounter('PHP', r'^(.+?[ <>\n])?php([ <>\n].+?)?', 'Languages'),
		TechCounter('Go', r'^(.+?[ <>\n])?go([ <>\n].+?)?$|^(.+?[ <>\n])?golang', 'Languages'),
		TechCounter('Ruby', r'^(.+?[ <>\n])?ruby([ <>\n].+?)?', 'Languages'),
		TechCounter('Objective-C', r'^(.+?[ <>\n])?objective[- ]?c([ <>\n].+?)?', 'Languages'),
		TechCounter('Scala', r'^(.+?[ <>\n])?scala([ <>\n].+?)?$', 'Languages'),
		TechCounter('Swift', r'^(.+?[ <>\n])?swift([- ]?\d)?([ <>\n].+?)?$', 'Languages'),
		TechCounter('R', r'^(.+?[ <>\n])?r([ <>\n].+?)?$', 'Languages'),
		TechCounter('COBOL', r'^(.+?[ <>\n])?cobol([ <>\n].+?)?', 'Languages'),
		TechCounter('Fortran', r'^(.+?[ <>\n])?fortran([ <>\n].+?)?', 'Languages'),
		TechCounter('Kotlin', r'^(.+?[ <>\n])?kotlin([ <>\n].+?)?', 'Languages'),
		TechCounter('XML', r'^(.+?[ <>\n])?xml([ <>\n].+?)?', 'Languages'),
		TechCounter('TypeScript', r'^(.+?[ <>\n])?typescript([ <>\n].+?)?', 'Languages'),
		TechCounter('JSON', r'^(.+?[ <>\n])?json([ <>\n].+?)?', 'Languages'),
		TechCounter('Perl', r'^(.+?[ <>\n])?perl([- ]?[56])?([ <>\n].+?)?$', 'Languages'),
		TechCounter('Less', r'^(.+?[ <>\n])?less([ <>\n].+?)?$', 'Languages'),
		TechCounter('Sass', r'^(.+?[ <>\n])?sass([ <>\n].+?)?$', 'Languages'),
		TechCounter('CoffeeScript', r'^(.+?[ <>\n])?coffeescript([ <>\n].+?)?', 'Languages'),
		TechCounter('Lisp', r'^(.+?[ <>\n])?lisp([ <>\n].+?)?$', 'Languages'),
		TechCounter('Pascal', r'^(.+?[ <>\n])?pascal([ <>\n].+?)?', 'Languages'),
		TechCounter('Dart', r'^(.+?[ <>\n])?dart([ <>\n].+?)?', 'Languages'),
		TechCounter('F', r'^(.+?[ <>\n])?f([ <>\n].+?)?$', 'Languages'),
		TechCounter('F#', r'^(.+?[ <>\n])?f#([ <>\n].+?)?', 'Languages'),
		TechCounter('Haskell', r'^(.+?[ <>\n])?haskell([ <>\n].+?)?', 'Languages'),
		TechCounter('Lua', r'^(.+?[ <>\n])?lua([ <>\n].+?)?$', 'Languages'),
		TechCounter('MATLAB', r'^(.+?[ <>\n])?matlab([ <>\n].+?)?', 'Languages'),
		TechCounter('PowerShell', r'^(.+?[ <>\n])?powershell([ <>\n].+?)?', 'Languages'),
		TechCounter('Elixir', r'^(.+?[ <>\n])?elixir([ <>\n].+?)?', 'Languages'),
		TechCounter('GraphQL', r'^(.+?[ <>\n])?graphql([ <>\n].+?)?', 'Languages'),
		TechCounter('D', r'^(.+?[ <>\n])?d([ <>\n].+?)?$', 'Languages'),


		TechCounter('React', r'^(.+?[ <>\n])?react(\.?js)?([ <>\n](?!native).+?)?$', 'Frameworks/CMS'),
		TechCounter('Node', r'^(.+?[ <>\n])?node(\.?js)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Spring', r'^(.+?[ <>\n])?spring([- ]?mvc)?([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Angular', r'^(.+?[ <>\n])?angular(\.?js)?\d?([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Rails', r'^(.+?[ <>\n])?(ruby[- ]?on[- ]?)?rails([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Django', r'^(.+?[ <>\n])?django([- ]?(?!rest)[ <>\n]+)?([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('ASP.NET', r'^(.+?[ <>\n])?asp.net([- ]?mvc)?([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('React Native', r'^(.+?[ <>\n])?react[- ]?native([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Ember', r'^(.+?[ <>\n])?ember(\.?js)([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Vue', r'^(.+?[ <>\n])?vue(\.?js)?([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Flask', r'^(.+?[ <>\n])?flask([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Django Rest Framework', r'^(.+?[ <>\n])?drf([ <>\n].+?)?$|^(.+?[ <>\n])?django[- ]?rest[- ]?framework([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('CakePHP', r'^(.+?[ <>\n])?cake(php)?([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Phoenix', r'^(.+?[ <>\n])?phoenix([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Express', r'^(.+?[ <>\n])?express(\.?js)?([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Backbone', r'^(.+?[ <>\n])?backbone(\.?js)?([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Drupal', r'^(.+?[ <>\n])?drupal([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Laravel', r'^(.+?[ <>\n])?laravel([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Symfony', r'^(.+?[ <>\n])?symfony([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Pyramid', r'^(.+?[ <>\n])?pyramid([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Sinatra', r'^(.+?[ <>\n])?sinatra([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('WordPress', r'^(.+?[ <>\n])?wordpress([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),
		TechCounter('Magento', r'^(.+?[ <>\n])?magento([- ]?framework)?([ <>\n].+?)?$', 'Frameworks/CMS'),


		TechCounter('.NET', r'^(.+?[ <>\n])?.net([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('Docker', r'^(.+?[ <>\n])?docker([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('AWS', r'^(.+?[ <>\n])?amazon([- ]?web[- ]?service(s)?)?([ <>\n].+?)?$|^(.+?[ <>\n])?aws([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('Azure', r'^(.+?[ <>\n])?azure([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('Java EE', r'^(.+?[ <>\n])?java[- ]?ee([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('Kubernetes', r'^(.+?[ <>\n])?kubernetes([ <>\n].+?)?$|^(.+?[ <>\n])?k8s([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('Apache', r'^(.+?[ <>\n])?apache([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('Google Cloud', r'^(.+?[ <>\n])?google[- ]?cloud([- ]?platform)?([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('Salesforce', r'^(.+?[ <>\n])?salesforce([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('Oracle', r'^(.+?[ <>\n])?oracle([ <>\n].+?)?$', 'Platforms/Web Services'),
		TechCounter('ROS', r'^(.+?[ <>\n])?ros([ <>\n].+?)?$|^(.+?[ <>\n])?robot[- ]?operating[- ]?system([ <>\n].+?)?$', 'Platforms/Web Services'),


		TechCounter('Git', r'^(.+?[ <>\n])?git([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Hadoop', r'^(.+?[ <>\n])?(apache[- ])?hadoop([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Apache Spark', r'^(.+?[ <>\n])?(apache[- ])?spark([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Jenkins', r'^(.+?[ <>\n])?jenkins([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Chef', r'^(.+?[ <>\n])?chef([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Redux', r'^(.+?[ <>\n])?(.+[- ])?redux([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Selenium', r'^(.+?[ <>\n])?selenium([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Jquery', r'^(.+?[ <>\n])?jquery([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Elasticsearch', r'^(.+?[ <>\n])?elasticsearch([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Puppet', r'^(.+?[ <>\n])?puppet([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Kafka', r'^(.+?[ <>\n])?(apache[- ])?kafka([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Spring Boot', r'^(.+?[ <>\n])?spring[- ]?boot([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Ansible', r'^(.+?[ <>\n])?ansible([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Jira', r'^(.+?[ <>\n])?(atlassian[- ]?)?jira([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('QT', r'^(.+?[ <>\n])?([ <>\n][- ]?)?qt([- ]?\d)?([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('TensorFlow', r'^(.+?[ <>\n])?tensorflow([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Ajax', r'^(.+?[ <>\n])?ajax([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Twitter Bootstrap', r'^(.+?[ <>\n])?(twitter[- ]?)?bootstrap([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Bulma', r'^(.+?[ <>\n])?bulma([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Cucumber', r'^(.+?[ <>\n])?cucumber([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('Terraform', r'^(.+?[ <>\n])?terraform([ <>\n].+?)?$', 'Libraries/Tools'),
		TechCounter('SQLAlchemy', r'^(.+?[ <>\n])?sqlalchemy([ <>\n].+?)?$', 'Libraries/Tools'),


		TechCounter('Unity3D', r'^(.+?[ <>\n])?unity(3d)?([ <>\n].+?)?$', 'Game Engines'),
		TechCounter('Unreal Engine', r'^(.+?[ <>\n])?unreal([- ]?engine)?([ <>\n].+?)?$', 'Game Engines'),
		TechCounter('Cry Engine', r'^(.+?[ <>\n])?cry([- ]?engine)?([ <>\n].+?)?$', 'Game Engines'),


		TechCounter('Web Services', r'^(.+?[ <>\n])?web[- ]?service(s)?([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Agile', r'^(.+?[ <>\n])?agile([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Cloud', r'^(.+?[ <>\n])?cloud([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('REST', r'^(.+?[ <>\n])?rest(ful)?[- ]?(architecture)?([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Machine Learning', r'^(.+?[ <>\n])?machine[- ]?learning([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('SysAdmin', r'^(.+?[ <>\n])?sysadmin([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('DevOps', r'^(.+?[ <>\n])?devops([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Testing', r'^(.+?[ <>\n])?testing([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Security', r'^(.+?[ <>\n])?([ <>\n]+)?[- ]?security([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('API ', r'^(.+?[ <>\n])?api([- ][ <>\n]+)?([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('User Interface', r'^(.+?[ <>\n])?ui([ <>\n].+?)?$|^(.+?[ <>\n])?user[- ]?interface([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Project Management', r'^(.+?[ <>\n])?project[- ]?management([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Microservices', r'^(.+?[ <>\n])?microservice([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('SaaS', r'^(.+?[ <>\n])?saas([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Continuous Integration', r'^(.+?[ <>\n])?ci([ <>\n].+?)?$|^(.+?[ <>\n])?continuous[- ]?integration([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Automation', r'^(.+?[ <>\n])?automation([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('QA', r'^(.+?[ <>\n])?qa([ <>\n].+?)?$|^(.+?[ <>\n])?quality[- ]?assurance([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Test Automation', r'^(.+?[ <>\n])?test[- ]?automation([ <>\n].+?)?$|^(.+?[ <>\n])?automated[- ]?tests?([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Object Oriented Programming', r'^(.+?[ <>\n])?oop([ <>\n].+?)?$|^(.+?[ <>\n])?object[- ]?oriented[- ]?programming([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Algorithms', r'^(.+?[ <>\n])?algorithm([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Scrum', r'^(.+?[ <>\n])?scrum([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('ETL', r'^(.+?[ <>\n])?etl([ <>\n].+?)?$|^(.+?[ <>\n])?extract[,\- ]?transform[,\- ]?load([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Embedded', r'^(.+?[ <>\n])?embedded([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Big Data', r'^(.+?[ <>\n])?big[- ]?data([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Computer Science', r'^(.+?[ <>\n])?cs([ <>\n].+?)?$|^(.+?[ <>\n])?computer[- ]?science([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('UX', r'^(.+?[ <>\n])?ux([ <>\n].+?)?$|^(.+?[ <>\n])?user[- ]?experience([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Test Driven Development', r'^(.+?[ <>\n])?tdd([ <>\n].+?)?$|^(.+?[ <>\n])?test[- ]?driven[- ]?develop(e)?ment([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Scalability', r'^(.+?[ <>\n])?scalability([ <>\n].+?)?$|^(.+?[ <>\n])?scalable([ <>\n].+?)?$|^(.+?[ <>\n])?scaling([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Backend', r'^(.+?[ <>\n])?back[- ]?end([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Frontend', r'^(.+?[ <>\n])?front[- ]?end([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Unit Testing', r'^(.+?[ <>\n])?unit[- ]?test(ing)?([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('MVC', r'^(.+?[ <>\n])?mvc([ <>\n].+?)?$|^(.+?[ <>\n])?model[- ]?view[- ]?controller([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Neural Networks', r'^(.+?[ <>\n])?neural[- ]?network', 'Concepts/Skills'),
		TechCounter('Debugging', r'^(.+?[ <>\n])?debug(ging)?([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Web Applications', r'^(.+?[ <>\n])?web[- ]?app(s)?(lication(s)?)?([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Design', r'^(.+?[ <>\n])?design([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Architecture', r'^([ <>\n].+?)?$(.+?[ <>\n])?architecture([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Functional Programming', r'^(.+?[ <>\n])?fp([ <>\n].+?)?$|^(.+?[ <>\n])?functional[- ]?programming([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Virtual Reality', r'^(.+?[ <>\n])?vr([ <>\n].+?)?$|^(.+?[ <>\n])?virtual[- ]?reality([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Cryptography', r'^(.+?[ <>\n])?crypto(graphy)?([ <>\n].+?)?$', 'Concepts/Skills'),
		TechCounter('Microservices', r'^(.+?[ <>\n])?micro[- ]?services?([ <>\n].+?)?$', 'Concepts/Skills'),


		TechCounter('Linux', r'^(.+?[ <>\n])?linux([ <>\n].+?)?$', 'Operating Systems'),
		TechCounter('Android', r'^(.+?[ <>\n])?android([ <>\n].+?)?$', 'Operating Systems'),
		TechCounter('iOS', r'^(.+?[ <>\n])?([a-z]+[- ])?ios|^(.+?[ <>\n])?iphone([ <>\n].+?)?$', 'Operating Systems'),
		TechCounter('Mobile', r'^(.+?[ <>\n])?mobile([ <>\n].+?)?$', 'Operating Systems'),
		TechCounter('Unix', r'^(.+?[ <>\n])?unix([ <>\n].+?)?$', 'Operating Systems'),
		TechCounter('Windows', r'^(.+?[ <>\n])?windows([ <>\n].+?)?$', 'Operating Systems'),


		TechCounter('MySQL', r'^(.+?[ <>\n])?mysql([ <>\n].+?)?$', 'Databases'),
		TechCounter('PostgreSQL', r'^(.+?[ <>\n])?postgre(sql)?s?([ <>\n].+?)?$', 'Databases'),
		TechCounter('Mongodb', r'^(.+?[ <>\n])?mongo(db)?([ <>\n].+?)?$', 'Databases'),
		TechCounter('SQL Server', r'^(.+?[ <>\n])?(microsoft[- ]?)?sql[- ]?server([ <>\n].+?)?$|^(.+?[ <>\n])?mssql([ <>\n].+?)?$', 'Databases'),
		TechCounter('NoSQL', r'^(.+?[ <>\n])?nosql([ <>\n].+?)?$', 'Databases'),
		TechCounter('Cassandra', r'^(.+?[ <>\n])?(apache[- ])?cassandra([ <>\n].+?)?$', 'Databases'),
		TechCounter('Redis', r'^(.+?[ <>\n])?redis([ <>\n].+?)?$', 'Databases'),
		TechCounter('SQLite', r'^(.+?[ <>\n])?sqlite([ <>\n].+?)?$', 'Databases'),
		TechCounter('MariaDB', r'^(.+?[ <>\n])?maria([- ]?db)?([ <>\n].+?)?$', 'Databases'),
	]